### ISSUE TITLE
 how to add regular user after instllation completes?

### ISSUE THREAD

**Issue by Piping** [christianh814/ocp4-upi-helpernode#14]
Is it possible to add more steps into this ansible playbook about setup a lab environment that have more functionality?

For example,  I have a hard time to setup a proper user account on openshift.

I know it can be done using ldap or htpasswd.

But it will be cool if the helper node also contains a ldap server and for openshift contains the proper cluster configuration.

**Comment by christianh814** [comment]
Adding an LDAP server to the helpernode is beyond the scope of what the helpernode was meant for. It was mean to just get you up and running. That being said, you can add users using htpasswd using the following...

1. Create the htpasswd file...

```
touch users.htpasswd
htpasswd  -b users.htpasswd developer openshift
```

2. Put it in a secret

```
oc create secret generic htpass-secret -n openshift-config --from-file=htpasswd=./users.htpasswd
```

3. Create an oauth config

```
cat <<EOF > cluster-oauth.yaml
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
 name: cluster
spec:
  identityProviders:
  - name: htpasswd_provider
    challenge: true
    login: true
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret
EOF
```
4.  Update the oauth setting

```
oc replace -f cluster-oauth.yaml
```

You should now be able to login as `developer` with the password `openshift` (**NOTE** this is a regular user)

To update this file with with a new user...


1. Update the file

```
htpasswd  -b users.htpasswd developer2 openshift
```

2. Get the encoding

```
base64 -w0 < users.htpasswd
```

3. Update the secret with the new encoding

```
oc edit secret htpass-secret -n openshift-config -o yaml
```

4. Trigger a reread by applying the unchanged oauth config

```
oc replace -f cluster-oauth.yaml
```
